### ISSUE TITLE
Set up separate runtime namespace

### ISSUE THREAD

**Issue by filmaj** [adobe/developer.adobe.com#120]
We should not piggyback on the io-solutions runtime accounts let's set up dedicated one for this website

**Comment by filmaj** [comment]
Done. Creds updated in circleci. I have creds and so does @stevengill.

**Comment by tripodsan** [comment]
do you want to use different namespaces for different strains using the same helix-config ?

**Comment by filmaj** [comment]
@tripodsan no I don't think so. Why do you ask?

**Comment by stevengill** [comment]
Actually, I could see a scenario where having difference namespaces for different strains makes sense. Hear me out.

If we have one runtime namespace for all strains, that means production and stage share the same runtime actions. That means if we make a change to an .htl/pre.js and do a deploy, it affects production and stage. 

Right now we have separate stage and production content by using specific git branches and strains. I think we want to do something similar for runtime actions. Being able to set a namespace per strain would give us this ability.

**Comment by tripodsan** [comment]
> That means if we make a change to an .htl/pre.js and do a deploy, it affects production and stage.

not anymore, since the actions are prefixed with the `sha` of the git commit of your code.

with the current version, we include the namespace an action is deployed to. and fastly uses the correct namespace prefix for a strain. we didn't implement (or we removed it again) authentication from fastly to i/o/ runtime, so that should not be a problem. but as soon as the action are private/protected, we would need a way to authenticate them differently per strain. I was thinking of using secure webactions instead of using the`wsk_token` which are easier to rotate, once compromised.
