### ISSUE TITLE
Hackathon: How do we write code and bring up services outside of Helix?

### ISSUE THREAD

**Issue by simonwex** [adobe/developer.adobe.com#32]
There will be functionality of the site that doesn't lean on Helix. How do we want to structure this? Do we still want to use Helix for content in these cases? What services do we want to use? How do we ensure operational stability?

Big questions, let's start to answer them with a prototype.

![image](https://user-images.githubusercontent.com/25260/48873823-d17f4b00-eda4-11e8-8a98-0b1b928f1688.png)

The above is an early, and likely throw-away wireframe as fodder. [Note: This isn't a place for wireframe feedback]

**Comment by filmaj** [comment]
Thanks for that @mwbrooks. I think we're trying to implement some of the examples you provided in other areas, for example, pulling the latest blog posts from the techblog (#85). Due to CORS restrictions there, we're forced to move that activity into the pipeline, so we do the work on the server(less)-side.

**Comment by filmaj** [comment]
Another thought is: any "glue code", API interactions, whatever, we can implement as runtime actions accessible from the web. I think that solves the "how do we write code and bring up services outside of helix" question. We have yet to come across this need so I am not sure we need to tackle it right away. I am going to close this issue but if I'm offside please re-open it.
