### ISSUE TITLE
Create IA document

### ISSUE THREAD

**Issue by simonwex** [adobe/developer.adobe.com#5]
Create a maintainable document that proposes a new IA for the current site content.

The goal with this document is to take it to the product owners andJen Gray who make up the IA governance group.

**Comment by simonwex** [comment]
Rendering of existing doc:
![image](https://user-images.githubusercontent.com/25260/47517644-b4a33680-d83d-11e8-88f9-5c844f4a250e.png)

**Comment by simonwex** [comment]
Step 1 in evolution: 
![image](https://user-images.githubusercontent.com/25260/47517682-d8667c80-d83d-11e8-96eb-9fc26e910e65.png)

**Comment by simonwex** [comment]
V0.3

![image](https://user-images.githubusercontent.com/25260/47517844-43b04e80-d83e-11e8-93d9-b762a16a7fcf.png)

Still very much a work in progress.

**Comment by ryanstewart** [comment]
One of my huge complaints about the current site is that "Documentation" isn't a top-level item. Nearly every developer site I come across has that as a top level item (developers.google.com being a notable example and may be a bigger conversation). In this flow, it looks like documentation is still 2 clicks away. I realize we've got some organizational strangeness going on, but I think this is a great thing to talk about and potentially solve now. A side question, is there a specific call to action we're imagining for the homepage?

The subtext of my question may lead to a bigger question: Is there a north star example you see for the site? I've always seen the goal of the site as being to get developers info they need so they can start building something, so the Console link as a main CTA, or documentation at the top level are things I'd associate with that. But @simonwex mentioned a larger goal of community that I haven't had a chance to dive into with him yet.

**Comment by cassiemc** [comment]
Here's a slightly adjusted IA file, feel free to comment directly on the design: https://xd.adobe.com/view/cd1e8ffb-3925-4cda-7baf-16a2b137e881-bb2f/screen/7541f587-93b3-43fa-a3c2-2713e1bb38c8/DevSite-IA-v0-1/

@ryanstewart That's probably where we want to get to, make the stuff that people want easy to get to! One of the things we're considering as we design (which may not be entirely obvious) is each product team's ownership of their own documentation and how the site will be maintained. I'm hoping there are smart ways that we can surface that from the landing pages or even the homepage so that it still feels easily accessible as well as a seamless experience. We are (currently) aiming to create templates so that documentation feels like documentation, no matter where in the product landscape you are. One thing to note is that we are lasering in on who our (current and aspirational) users are and how they like to find/see stuff, so we'll be talking that through in our stakeholder interviews. Appreciate your insight here. We're also doing a bunch of thorough competitor audits so sites like google, facebook, dropbox, sketch, box, a bunch of others, are all on that list.

Console will definitely be emphasized likely no matter where you are on the site! We'll work through definitely cta's when we get to designing ux for each section.

Hope that answers some of the questions or at least supports more conversation. :)

**Comment by lcrabb** [comment]
A few thoughts:
* I like the direction. Nice job so far.
* I agree with Cassie that Blog should be under Community.
* How do Forums and Support relate? I think of Forums as part of Support.
* Is there a way to reduce the number of clicks to get to API documentation? I don't have the answer but hoping we can find a way to organize many different products and make it intuitive for developers.

**Comment by ktukker-adobe** [comment]
Hi team, good to see the thinking. The IA is very traditional. Adobe developers is a broad bucket. I would like to see it more actionable for a developer. For example Azure: https://docs.microsoft.com/en-us/azure/index?view=azure-cli-latest

Twitter developer: https://developer.twitter.com/content/developer-twitter/en.html

Google cloud: https://cloud.google.com/

The challenge that I see is that the examples above are all starting from a Product perspective, where we start from a Brand (Adobe developers). I first need to find my way as a developer 'where I fit in' to get to what is actionable for me.

Suggestion: think different

**Comment by stevengill** [comment]
@ktukker-adobe That Azure page you linked took me a few clicks to find if I started at developers.microsoft.com. 

Instead of using cloud.google.com as a comparable, why not https://developers.google.com/. This site takes a google developer perspective over product perspective. The nice thing about it though is that it highlights its products and makes it easy to go to the product developer page for that product perspective. I think that is what they are trying to do with this new site right?

**Comment by cassiemc** [comment]
FYI here is the updated IA. https://xd.adobe.com/view/8ce0fa8e-c777-4ca7-4675-c29614d84b86-fad1/screen/26c8152e-2459-4c09-a18c-90890abdfffc/DevSite-IA-v0-4-Logged-out-2

I recognize there was some feedback / discussion around this version at the hackathon. Is anyone able to please document the feedback so I can move this issue forward (and potentially – I'm being optimistic! – close)? @simonwex

**Comment by cassiemc** [comment]
Pasting the updated IA in here for easy access. Do we need a section specifically for partners/enterprise? This could perhaps be addressed in the Use Cases section.

![iav5](https://user-images.githubusercontent.com/1186326/50183446-18972800-02e0-11e9-8ec2-698e9f9ca0fa.png)

**Comment by filmaj** [comment]
As part of my incessant issue tracker cleanup, I want to see if we can a) host the IA document as part of this repository and b) close the issue?

**Comment by cassiemc** [comment]
@filmaj I'm fine with hosting it as part of the repo, how does one do that? And I'm more than fine with closing the issue! There does not seem anything imminently actionable on it.

Here are the files (XD source in the zip, as well as a static png here). I've added a large WIP so that others know it is a working document.

![devsite ia v0 5 wip](https://user-images.githubusercontent.com/1186326/53577256-536cd600-3b43-11e9-9475-9a91c293f297.png)
[Adobe Developers IA v5 - WIP.zip](https://github.com/adobe/developer.adobe.com/files/2915648/Adobe.Developers.IA.v5.-.WIP.zip)

**Comment by filmaj** [comment]
@cassiemc thanks for sharing the zip! I've added it to the repo in 7b995cf under the `xd/` folder. May I ask that in the future, if y'all end up making changes to the file, that you update the file revisioned in this repository? I can show you how to do that if you'd find that helpful.
