### ISSUE TITLE
Running multiple strains locally (`hlx up`) no workie

### ISSUE THREAD

**Issue by filmaj** [adobe/developer.adobe.com#61]
Due to us using bleeding edge multi-strain helix shtuff. So likely a helix bug/enhancement.

**Comment by filmaj** [comment]
We fixed this in the december hackathon, but it seems to have come back to have bit us now. @stevengill can you confirm this is still an issue?

**Comment by stevengill** [comment]
What's the issue? `hlx up` stopped working for you? For the main strain or other strains?

**Comment by stevengill** [comment]
I ran into a similar issue this week when I updated the helix-pipeline dependency in our package.json. You didn't do that did you?

**Comment by filmaj** [comment]
The original bug here was reported in december as multi-strain local `hlx up` not working. Is that still the case?

**Comment by stevengill** [comment]
Ahh sorry I misunderstood and thought you meant `hlx up` in general was broken. 

Locally testing multiple strains is definitely still borked. But it kinda works.

- Add the `--host` flag to `hlx up` command to get strain resolution to work.

```hlx up --host www.adobe.io```

With the above command, you could go to urls for the appropriate strains.

```htts://localhost:3000/launch/docs/README.md```

The remaining issues are with the dispatcher. It doesn't load the right files and loses mount points. @tripodsan is working on a fix by passing in a new argument we could use in the dispatcher to fix mounting. See https://github.com/adobe/helix-pipeline/issues/170

**Comment by stevengill** [comment]
So the code to write the nav with absolute urls already exists in summary_html.pre.js. It was just commented out. The problem is, we need the mount points to rewrite the link properly. 

Four places I need the mount points currently:
1) the dispatcher
2) Before loading summary.htl, we need to figure out the location of summary.md. Need to add the mount point in there
3) The side nav in the docs (where we convert the links to absolute links
4) Any image tags in the content markdown repo. They link locally to images in the assets directory locally in their own repos. These links need to be rewritten with mount points.

**Comment by filmaj** [comment]
So, this issue, with regards to multiple strains running locally: this is solved now. Closing.
